---
- name: Install Adventureland
  hosts: master-servers
  become: yes  # Run tasks as a superuser (root)
  roles: 
  - dependencies
  - storage
  - appengine
  - services
  - adventureland-master
  
- name: Install Adventureland
  hosts: game-servers
  become: yes  # Run tasks as a superuser (root)
  roles: 
  - dependencies
  - services
  - adventureland-server