---
- name: Install Adventureland
  hosts: master-servers
  become: yes  # Run tasks as a superuser (root)
  roles: 
  - storage
  - pip
  - appengine
  - service
  - adventureland-master
  
- name: Install Adventureland
  hosts: game-servers
  become: yes  # Run tasks as a superuser (root)
  roles: 
  - service
  - adventureland-master