- name: Check if storage volume is mounted
  become: true
  block:
    - name: Get mount information for the specified volume
      command: "mount | grep '{{ mount_point }}'"
      register: mount_info
      changed_when: false
      ignore_errors: true

    - name: Check if the volume is mounted
      set_fact:
        storage_mounted: "{{ mount_info.rc == 0 }}"

- name: Notify handler to mount the volume if not already mounted
  when: not volume_mounted
  notify: Mount Volume