---
- name: Get local file checksums
  find:
    paths: ./
    recurse: yes
    exclude_paths: "{{ excluded_paths }}"
  register: local_files

- name: Get remote file checksums
  find:
    paths: /opt/adventureland
    recurse: yes
    exclude_paths: "{{ excluded_paths }}"
  register: remote_files

- name: Compare file checksums
  assert:
    that: "{{ item.stat.md5 == remote_files.files[0].stat.md5 }}"
    fail_msg: "Files are different!"
  loop: "{{ local_files.files }}"
  loop_control:
    label: "{{ item.path }}"
  notify: Copy Files