---
- name: Create Master Server service
  template:
    src: master_server.service.j2
    dest: "/etc/systemd/system/master_server.service"
  notify: Reload Services

- name: Create Game Server service
  template:
    src: game_server.service.j2
    dest: "/etc/systemd/system/game_server.service"
  notify: Reload Services