write_files:
- content: |
    ${install_sh}
  path: /opt/install.sh

runcmd:
  - if ${run_master}; then 
  - mkdir /opt/storage
  - mount -o discard,defaults /dev/disk/by-id/scsi-0HC_Volume_${volume_id} /opt/storage
  - echo "/dev/disk/by-id/scsi-0HC_Volume_${volume_id} /opt/storage ext4 discard,nofail,defaults 0 0" >> /etc/fstab
  - fi

