---
- name: Upload Game files
  ansible.posix.synchronize:
    src: ./../../../../../
    dest: /opt/adventureland
    delete: true
    rsync_opts:
      - "--exclude=./cicd"
      - "--exclude=./.github"
      
- name: Install npm Packages
  shell: 
    chdir: /opt/adventureland/node
    cmd: npm install
