name: Deploy Infrastructure and Run Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.1.0 # You can specify the version you want to use

      - name: Initialize Terraform
        working-directory: ./cicd/infra
        run: terraform init
        env:
          TF_HTTP_ADDRESS: ${{ secrets.TF_HTTP_ADDRESS }}
          TF_HTTP_USERNAME: ${{ secrets.TF_HTTP_USERNAME }}
          TF_HTTP_PASSWORD: ${{ secrets.TF_HTTP_PASSWORD }}
          
      - name: Terraform Apply
        working-directory: ./cicd/infra
        run: terraform apply -auto-approve -input=false
        env:
          TF_VAR_hcloud_token: ${{ secrets.hcloud_token }}
          TF_HTTP_ADDRESS: ${{ secrets.TF_HTTP_ADDRESS }}
          TF_HTTP_USERNAME: ${{ secrets.TF_HTTP_USERNAME }}
          TF_HTTP_PASSWORD: ${{ secrets.TF_HTTP_PASSWORD }}

      

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Run Ansible Playbook
        uses: aimerib/ansible-playwright@v2.7.7
        with:
          playbook: cicd/setup/playbooks/deploy.yml
          directory: ./
          key: ${{ secrets.HETZNER_PRIVATE_KEY }}
          inventory: cicd/setup/inventory.yml
          known_hosts: .known_hosts
          options: |
            --verbose